version: '3.8'
services:
  database:
    image: postgres:13.1
    restart: always
    container_name: posgres_db
    ports:
      - '8080:5432'
    environment:
      - POSTGRES_USER=movie_dev
      - POSTGRES_PASSWORD=movie_dev_pwd
      - POSTGRES_DB=movie_dev
      - DATABASE_HOST=database
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U movie_dev']
      interval: 40s
      timeout: 40s
      start_period: 40s
      retries: 5
    volumes:
      - ./posg.sql:/docker-entrypoint-initdb.d/posg.sql
      - data:/var/lib/postgresql/data
    networks:
      - fullstack

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      database:
        condition: service_healthy
    networks:
      - fullstack
    ports:
      - '3001:3001'

volumes:
  data:

networks:
  fullstack:
    driver: bridge
